from django.core.management.base import BaseCommand
from properties.models import Property
from decimal import Decimal


class Command(BaseCommand):
    help = 'Seeds the database with sample property data'

    def handle(self, *args, **kwargs):
        self.stdout.write('Seeding properties...')
        
        properties_data = [
            {
                'title': 'Luxury Modern Villa',
                'description': 'Beautiful modern villa with stunning ocean views. Features high-end finishes, smart home technology, and a private infinity pool.',
                'property_type': 'house',
                'status': 'sale',
                'price': Decimal('2500000.00'),
                'address': '123 Ocean Drive',
                'city': 'Miami',
                'state': 'Florida',
                'zip_code': '33139',
                'bedrooms': 5,
                'bathrooms': Decimal('4.5'),
                'square_feet': 4500,
                'lot_size': 8000,
                'year_built': 2022,
                'parking_spaces': 3,
                'has_garage': True,
                'has_pool': True,
                'has_garden': True,
                'featured': True,
            },
            {
                'title': 'Downtown Luxury Apartment',
                'description': 'Spacious apartment in the heart of downtown with panoramic city views. Walking distance to restaurants, shops, and entertainment.',
                'property_type': 'apartment',
                'status': 'rent',
                'price': Decimal('3500.00'),
                'address': '456 Main Street, Unit 2501',
                'city': 'New York',
                'state': 'New York',
                'zip_code': '10001',
                'bedrooms': 2,
                'bathrooms': Decimal('2.0'),
                'square_feet': 1800,
                'year_built': 2020,
                'parking_spaces': 1,
                'has_garage': True,
                'has_pool': False,
                'has_garden': False,
                'featured': True,
            },
            {
                'title': 'Charming Suburban Home',
                'description': 'Perfect family home in a quiet neighborhood with excellent schools. Updated kitchen, hardwood floors, and large backyard.',
                'property_type': 'house',
                'status': 'sale',
                'price': Decimal('650000.00'),
                'address': '789 Maple Avenue',
                'city': 'Austin',
                'state': 'Texas',
                'zip_code': '78701',
                'bedrooms': 4,
                'bathrooms': Decimal('3.0'),
                'square_feet': 2800,
                'lot_size': 6500,
                'year_built': 2015,
                'parking_spaces': 2,
                'has_garage': True,
                'has_pool': False,
                'has_garden': True,
                'featured': False,
            },
            {
                'title': 'Modern Condo with City Views',
                'description': 'Stylish condo with floor-to-ceiling windows and modern amenities. Building features gym, rooftop terrace, and concierge service.',
                'property_type': 'condo',
                'status': 'sale',
                'price': Decimal('450000.00'),
                'address': '321 Park Boulevard, #1205',
                'city': 'Seattle',
                'state': 'Washington',
                'zip_code': '98101',
                'bedrooms': 2,
                'bathrooms': Decimal('2.0'),
                'square_feet': 1400,
                'year_built': 2019,
                'parking_spaces': 1,
                'has_garage': True,
                'has_pool': False,
                'has_garden': False,
                'featured': False,
            },
            {
                'title': 'Cozy Studio Apartment',
                'description': 'Affordable studio in a great location. Perfect for students or young professionals. Close to public transportation.',
                'property_type': 'apartment',
                'status': 'rent',
                'price': Decimal('1200.00'),
                'address': '555 College Street, Apt 3B',
                'city': 'Boston',
                'state': 'Massachusetts',
                'zip_code': '02115',
                'bedrooms': 0,
                'bathrooms': Decimal('1.0'),
                'square_feet': 550,
                'year_built': 2010,
                'parking_spaces': 0,
                'has_garage': False,
                'has_pool': False,
                'has_garden': False,
                'featured': False,
            },
            {
                'title': 'Spacious Townhouse',
                'description': 'Three-story townhouse with modern design and private patio. Great for entertaining with open floor plan.',
                'property_type': 'townhouse',
                'status': 'sale',
                'price': Decimal('725000.00'),
                'address': '888 Elm Street',
                'city': 'San Francisco',
                'state': 'California',
                'zip_code': '94102',
                'bedrooms': 3,
                'bathrooms': Decimal('2.5'),
                'square_feet': 2200,
                'lot_size': 1500,
                'year_built': 2018,
                'parking_spaces': 2,
                'has_garage': True,
                'has_pool': False,
                'has_garden': True,
                'featured': True,
            },
            {
                'title': 'Prime Commercial Space',
                'description': 'High-traffic commercial property perfect for retail or office use. Ample parking and excellent visibility.',
                'property_type': 'commercial',
                'status': 'rent',
                'price': Decimal('8500.00'),
                'address': '999 Business Boulevard',
                'city': 'Chicago',
                'state': 'Illinois',
                'zip_code': '60601',
                'bedrooms': 0,
                'bathrooms': Decimal('2.0'),
                'square_feet': 3500,
                'year_built': 2016,
                'parking_spaces': 10,
                'has_garage': False,
                'has_pool': False,
                'has_garden': False,
                'featured': False,
            },
            {
                'title': 'Waterfront Estate',
                'description': 'Magnificent waterfront estate with private dock and beach access. Gourmet kitchen, wine cellar, and home theater.',
                'property_type': 'house',
                'status': 'sale',
                'price': Decimal('4200000.00'),
                'address': '100 Lakeside Drive',
                'city': 'Lake Tahoe',
                'state': 'California',
                'zip_code': '96150',
                'bedrooms': 6,
                'bathrooms': Decimal('5.5'),
                'square_feet': 6800,
                'lot_size': 15000,
                'year_built': 2021,
                'parking_spaces': 4,
                'has_garage': True,
                'has_pool': True,
                'has_garden': True,
                'featured': True,
            },
        ]
        
        created_count = 0
        for prop_data in properties_data:
            property_obj, created = Property.objects.get_or_create(
                title=prop_data['title'],
                defaults=prop_data
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'Created: {property_obj.title}'))
            else:
                self.stdout.write(self.style.WARNING(f'Already exists: {property_obj.title}'))
        
        self.stdout.write(self.style.SUCCESS(f'\nSuccessfully created {created_count} properties!'))
