# Generated by Django 6.0.3 on 2026-06-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='land_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size of the land', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_size_unit',
            field=models.CharField(blank=True, choices=[('plots', 'Plots'), ('acres', 'Acres'), ('sqft', 'Square Feet'), ('sqm', 'Square Meters'), ('hectares', 'Hectares')], default='plots', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
